/**
 * Random display names for guest players, drawn from Magic's cast of
 * legendary characters. Four people tapping "Play as Guest" at the same
 * table used to all be called "Guest"; now they're Krenko, Tamiyo, Squee,
 * and Yargle, which is both distinguishable and funnier.
 *
 * Collisions are possible (two Jaces at one table) but rare at 4-8 players
 * against a pool this size, mildly amusing when they happen, and
 * self-serviceable now that players can rename themselves in-game.
 */
const GUEST_NAMES = [
  'Ajani',
  'Angrath',
  'Anax',
  'Arlinn',
  'Ashiok',
  'Atraxa',
  'Aurelia',
  'Bolas',
  'Borborygmos',
  'Brimaz',
  'Calix',
  'Chandra',
  'Dack',
  'Davriel',
  'Domri',
  'Dovin',
  'Edgar',
  'Elspeth',
  'Emmara',
  'Emrakul',
  'Erebos',
  'Feather',
  'Freyalise',
  'Geralf',
  'Gerrard',
  'Gideon',
  'Gisa',
  'Gix',
  'Glissa',
  'Grumgully',
  'Hanna',
  'Heliod',
  'Huatli',
  'Isperia',
  'Jace',
  'Jaya',
  'Jhoira',
  'Jodah',
  'Karn',
  'Kasmina',
  'Kaya',
  'Keranos',
  'Kinnan',
  'Kiora',
  'Klothys',
  'Koth',
  'Kozilek',
  'Krenko',
  'Kruphix',
  'Kytheon',
  'Lavinia',
  'Liliana',
  'Lurrus',
  'Lutri',
  'Memnarch',
  'Mirri',
  'Mishra',
  'Muldrotha',
  'Multani',
  'Nahiri',
  'Narset',
  'Nissa',
  'Niv-Mizzet',
  'Nylea',
  'Obosh',
  'Oko',
  'Olivia',
  'Omnath',
  'Pharika',
  'Purphoros',
  'Ral',
  'Rakdos',
  'Rofellos',
  'Saheeli',
  'Sarkhan',
  'Sisay',
  'Slobad',
  'Sorin',
  'Squee',
  'Tamiyo',
  'Tatyova',
  'Teferi',
  'Tezzeret',
  'Thassa',
  'Tibalt',
  'Titania',
  'Ugin',
  'Ulamog',
  'Urza',
  'Venser',
  'Vivien',
  'Vorel',
  'Vraska',
  'Windgrace',
  'Xenagos',
  'Yargle',
  'Yawgmoth',
  'Yisan',
  'Yorion',
  'Zegana',
];

export function randomGuestName(): string {
  return GUEST_NAMES[Math.floor(Math.random() * GUEST_NAMES.length)];
}
